package pojo;

import static com.sun.faces.facelets.util.Path.context;
import dao.DAOAdmin;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

/**
 * Admin generated by hbm2java
 */
@ManagedBean
public class Admin implements java.io.Serializable {

    private Integer idAdmin;
    private String nama;
    private String email;
    private String password;
    private Admin loggedInAdmin;
    private String nameMessage;
    private String selectedMenu;

    public Admin() {
    }

    public Admin(String nama, String email, String password) {
        this.nama = nama;
        this.email = email;
        this.password = password;
    }
    
    public String getSelectedMenu() {
        return selectedMenu;
    }

    public void setSelectedMenu(String selectedMenu) {
        this.selectedMenu = selectedMenu;
    }


    public Integer getIdAdmin() {
        return this.idAdmin;
    }

    public void setIdAdmin(Integer idAdmin) {
        this.idAdmin = idAdmin;
    }

    public String getNama() {
        return this.nama;
    }

    public void setNama(String nama) {
        this.nama = nama;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Admin getLoggedInAdmin() {
        return loggedInAdmin;
    }

    public void setLoggedInAdmin(Admin loggedInAdmin) {
        this.loggedInAdmin = loggedInAdmin;
    }

    public String getNameMessage() {
        return nameMessage;
    }

    public void setNameMessage(String nameMessage) {
        this.nameMessage = nameMessage;
    }
 

    public String login() {
    FacesContext context = FacesContext.getCurrentInstance();

    try {
        DAOAdmin adao = new DAOAdmin();
        List<Admin> admins = adao.login(email, password);

        if (admins != null && !admins.isEmpty()) {
            Admin admin = admins.get(0);
            email = admin.getEmail(); // Ganti prod dengan admin sesuai kelas entitas yang benar
            password = admin.getPassword(); // Ganti prod dengan admin sesuai kelas entitas yang benar

            context.getExternalContext().getSessionMap().put("email", email); // Perbaiki "emai;" menjadi "email"
            return "loginsuccess";
        } else {
            context.addMessage(null, new FacesMessage("Login failed. Please check your email and password."));
            return null; // Redirect to the login error page
        }
    } catch (Exception e) {
        e.printStackTrace(); // Cetak kesalahan untuk debug
        context.addMessage(null, new FacesMessage("An error occurred during login."));
        return null; // Redirect to the login error page
    }
}



    public void validateName() {
        if (nama != null && !nama.matches("^[A-Za-z ]+$")) {
            nameMessage = "Nama hanya boleh mengandung huruf dan spasi.";
        } else {
            nameMessage = "";
        }
    }

    public String logout() {
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
        return "index";
    }
    
   public String createLS() {
        return "cls";
    }
    
    public String deleteLS() {
        return "dls";
    }
    
    public String searchLS() {
        return "sels";
    }
    
    public String showLS() {
        return "shls";
    }
    
    public String updateLS() {
        return "uls";
    }
    
    public String createSS() {
        return "css";
    }
    
    public String deleteSS() {
        return "dss";
    }
    
    public String searchSS() {
        return "sess";
    }
    
    public String showSS() {
        return "shss";
    }
    
    public String updateSS() {
        return "uss";
    }
    
    public String createCourse() {
        return "cc";
    }
    
    public String deleteCourse() {
        return "dc";
    }
    
    public String searchCourse() {
        return "sec";
    }
    
    public String showCourse() {
        return "shc";
    }
    
    public String updateCourse() {
        return "uc";
    }
    
    public String createLecturer() {
        return "cl";
    }
    
    public String deleteLecturer() {
        return "dl";
    }
    
    public String searchLecturer() {
        return "sel";
    }
    
    public String showLecturer() {
        return "success";
    }
    
    public String updateLecturer() {
        return "ul";
    }
    
    public String createSchedule() {
        return "csc";
    }
    
    public String deleteSchedule() {
        return "dsc";
    }
    
    public String searchSchedule() {
        return "sesc";
    }
    
    public String showSchedule() {
        return "shsc";
    }
    
    public String updateSchedule() {
        return "usc";
    }
    
    public String createStudent() {
        return "cs";
    }
    
    public String deleteStudent() {
        return "ds";
    }
    
    public String searchStudent() {
        return "ses";
    }
    
    public String showStudent() {
        return "shs";
    }
    
    public String updateStudent() {
        return "us";
    }
    
    public String createSubject() {
        return "csb";
    }
    
    public String deleteSubject() {
        return "dsb";
    }
    
    public String searchSubject() {
        return "sesb";
    }
    
    public String showSubject() {
        return "shsb";
    }
    
    public String updateSubject() {
        return "usb";
    }
    
    public String navigateToAllLogin() {
    return "allLoginRedirect";
}
    
    public String alogin() {
        return "al";
    }
    
    public String slogin() {
        return "sl";
    }
    
    public String sregister() {
        return "sr";
    }
    
    public String llogin() {
        return "ll";
    }
    
    public String lregister() {
        return "lr";
    }

}
